[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
license = "MIT"
description = "{{description}}"
{% if crate_type == "bin" %}
[profile.release]
codegen-units = 1
lto = true
{% endif %}
[dependencies]
